version: '3'
services:  
  db-dev.geoblacklight-local:
    image: postgres:12
    restart: always
    ports:
        - 5432:5432
    #networks: ['stack']
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tester1
      - POSTGRES_DB=geogm_development
      - environment=dev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
  geoblacklight:
    build: .
    ports:
      - "3000:3000"
    environment:
      - username=postgres
      - password=tester1
      - database=geogm_development
      - environment=dev
  solr-dev.geoblacklight-local:
    image: "acornwe3/solr-test:v11"
    ports:
      - "8983:8983"